Task 3

1) Create random data from 10, 100
    - rows should be 10
    - columns should 4
    - all the data should be integers

2) Compute the percentage value in the data
    - 4's percentage is 0.04
    - this should be implemented for the entire data frame
    - use apply() or map()

3) Replace values that are less than 50 with the square root of itself
    - implement this for the entire data
    - use apply() or map()
    - you should use conditions here

4) How do implement the 3rd task without using apply() and map() in just one line?

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=np.random.randint(10,100,size=(10,4))
print(a)

[[12 77 85 60]
 [48 11 49 23]
 [89 29 61 73]
 [27 28 56 48]
 [63 22 79 59]
 [23 58 47 71]
 [54 21 92 81]
 [70 96 99 29]
 [35 74 97 90]
 [35 87 26 40]]


In [ ]:
#1
df=pd.DataFrame(a)
print(df)

    0   1   2   3
0  12  77  85  60
1  48  11  49  23
2  89  29  61  73
3  27  28  56  48
4  63  22  79  59
5  23  58  47  71
6  54  21  92  81
7  70  96  99  29
8  35  74  97  90
9  35  87  26  40


In [ ]:
#2
def percentage(x):
  return x/100

percent=df.apply(percentage, axis=0)
print(percent)

      0     1     2     3
0  0.12  0.77  0.85  0.60
1  0.48  0.11  0.49  0.23
2  0.89  0.29  0.61  0.73
3  0.27  0.28  0.56  0.48
4  0.63  0.22  0.79  0.59
5  0.23  0.58  0.47  0.71
6  0.54  0.21  0.92  0.81
7  0.70  0.96  0.99  0.29
8  0.35  0.74  0.97  0.90
9  0.35  0.87  0.26  0.40


In [ ]:
#3
r=pd.DataFrame()
for i in df:
  r[i]=df[i].apply(lambda x: x if x>50 else np.sqrt(x))
print(r)

           0          1          2          3
0   3.464102  77.000000  85.000000  60.000000
1   6.928203   3.316625   7.000000   4.795832
2  89.000000   5.385165  61.000000  73.000000
3   5.196152   5.291503  56.000000   6.928203
4  63.000000   4.690416  79.000000  59.000000
5   4.795832  58.000000   6.855655  71.000000
6  54.000000   4.582576  92.000000  81.000000
7  70.000000  96.000000  99.000000   5.385165
8   5.916080  74.000000  97.000000  90.000000
9   5.916080  87.000000   5.099020   6.324555


In [ ]:
#4
t=pd.DataFrame()
t=df.applymap(lambda x: x if x>50 else np.sqrt(x))
print(t)

           0          1          2          3
0   3.464102  77.000000  85.000000  60.000000
1   6.928203   3.316625   7.000000   4.795832
2  89.000000   5.385165  61.000000  73.000000
3   5.196152   5.291503  56.000000   6.928203
4  63.000000   4.690416  79.000000  59.000000
5   4.795832  58.000000   6.855655  71.000000
6  54.000000   4.582576  92.000000  81.000000
7  70.000000  96.000000  99.000000   5.385165
8   5.916080  74.000000  97.000000  90.000000
9   5.916080  87.000000   5.099020   6.324555
